-- Customers (visitors: individuals / institutions), signatories, KYC documents.
-- Aadhaar: encrypted (libsodium) + sha256 hash for duplicate checks + last 4 digits for display.

CREATE TABLE customers (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    unique_id        VARCHAR(30)  NULL COMMENT 'CMN-KTR-{I|N}-{YYYY}-{00001}, issued at KYC submission',
    centre_id        BIGINT UNSIGNED NOT NULL,
    account_id       BIGINT UNSIGNED NULL,
    type             VARCHAR(12)  NOT NULL COMMENT 'individual | institution',
    sub_category     VARCHAR(30)  NULL COMMENT 'App\\Enums\\CustomerSubCategory',
    name             VARCHAR(190) NOT NULL,
    email            VARCHAR(190) NULL,
    mobile           VARCHAR(20)  NULL,
    nationality      VARCHAR(60)  NOT NULL DEFAULT 'Indian',
    address          VARCHAR(500) NULL,
    city             VARCHAR(100) NULL,
    pincode          VARCHAR(10)  NULL,
    state_code       CHAR(2)      NULL COMMENT 'GST state code, 32 = Kerala',
    profile          TEXT NULL,
    pan              CHAR(10)     NULL,
    gstin            CHAR(15)     NULL,
    tan              CHAR(10)     NULL,
    aadhaar_enc      VARBINARY(255) NULL,
    aadhaar_hash     CHAR(64)     NULL,
    aadhaar_last4    CHAR(4)      NULL,
    passport_no      VARCHAR(20)  NULL,
    kyc_status       VARCHAR(20)  NOT NULL DEFAULT 'not_submitted' COMMENT 'App\\Enums\\KycStatus',
    kyc_submitted_at DATETIME NULL,
    kyc_verified_by  BIGINT UNSIGNED NULL,
    kyc_verified_at  DATETIME NULL,
    kyc_remarks      VARCHAR(500) NULL,
    consent_at       DATETIME NULL COMMENT 'Aadhaar / DPDP consent timestamp',
    registered_via   VARCHAR(12)  NOT NULL DEFAULT 'online' COMMENT 'online | reception',
    registered_by    BIGINT UNSIGNED NULL COMMENT 'staff_users.id for assisted registration',
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_customers_unique_id (unique_id),
    UNIQUE KEY uq_customers_account (account_id),
    KEY idx_customers_email (email),
    KEY idx_customers_mobile (mobile),
    KEY idx_customers_aadhaar_hash (aadhaar_hash),
    KEY idx_customers_pan (pan),
    KEY idx_customers_gstin (gstin),
    KEY idx_customers_kyc (kyc_status),
    KEY idx_customers_name (name),
    CONSTRAINT fk_customers_centre FOREIGN KEY (centre_id) REFERENCES centres (id) ON DELETE RESTRICT,
    CONSTRAINT fk_customers_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL,
    CONSTRAINT fk_customers_verified_by FOREIGN KEY (kyc_verified_by) REFERENCES staff_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_customers_registered_by FOREIGN KEY (registered_by) REFERENCES staff_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE customer_signatories (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id    BIGINT UNSIGNED NOT NULL,
    name           VARCHAR(150) NOT NULL,
    designation    VARCHAR(100) NULL,
    email          VARCHAR(190) NULL,
    mobile         VARCHAR(20)  NULL,
    aadhaar_enc    VARBINARY(255) NULL,
    aadhaar_hash   CHAR(64) NULL,
    aadhaar_last4  CHAR(4)  NULL,
    is_primary     TINYINT(1) NOT NULL DEFAULT 1,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_signatories_customer (customer_id),
    KEY idx_signatories_aadhaar_hash (aadhaar_hash),
    CONSTRAINT fk_signatories_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE customer_documents (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id       BIGINT UNSIGNED NOT NULL,
    doc_type          VARCHAR(30)  NOT NULL COMMENT 'App\\Enums\\DocumentType',
    original_name     VARCHAR(255) NULL,
    file_path         VARCHAR(255) NOT NULL COMMENT 'Relative to storage/uploads (never public)',
    mime              VARCHAR(100) NOT NULL,
    size              INT UNSIGNED NOT NULL,
    uploaded_by_type  VARCHAR(10)  NOT NULL COMMENT 'account | staff',
    uploaded_by       BIGINT UNSIGNED NULL,
    verified_by       BIGINT UNSIGNED NULL,
    verified_at       DATETIME NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_documents_customer (customer_id, doc_type),
    CONSTRAINT fk_documents_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
    CONSTRAINT fk_documents_verified_by FOREIGN KEY (verified_by) REFERENCES staff_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
