-- Bookings, booked seats and facilities, check-ins, payments.
-- Double-booking prevention (batch 4): lock `seats` rows FOR UPDATE inside a transaction and
-- check overlapping booking_seats (start_date/end_date are denormalised for that query) and seat_holds.

CREATE TABLE bookings (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_no        VARCHAR(20)  NOT NULL COMMENT 'BK-{YYYY}-{000001}',
    centre_id         BIGINT UNSIGNED NOT NULL,
    customer_id       BIGINT UNSIGNED NOT NULL,
    source            VARCHAR(12)  NOT NULL COMMENT 'online | reception',
    seat_category_id  BIGINT UNSIGNED NOT NULL,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    start_time        TIME NULL COMMENT 'conference room (hourly) only',
    end_time          TIME NULL,
    duration_unit     VARCHAR(10)  NOT NULL COMMENT 'day | month | hour',
    duration_qty      DECIMAL(8,2) NOT NULL DEFAULT 1,
    seats_count       SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    payment_rule      VARCHAR(20)  NOT NULL COMMENT 'advance | security_deposit',
    subtotal          DECIMAL(12,2) NOT NULL DEFAULT 0,
    facilities_total  DECIMAL(12,2) NOT NULL DEFAULT 0,
    gst_total         DECIMAL(12,2) NOT NULL DEFAULT 0,
    grand_total       DECIMAL(12,2) NOT NULL DEFAULT 0,
    deposit_amount    DECIMAL(12,2) NOT NULL DEFAULT 0,
    status            VARCHAR(12)  NOT NULL DEFAULT 'requested' COMMENT 'App\\Enums\\BookingStatus',
    requested_by      BIGINT UNSIGNED NULL COMMENT 'accounts.id for online requests',
    created_by        BIGINT UNSIGNED NULL COMMENT 'staff_users.id for reception bookings',
    approved_by       BIGINT UNSIGNED NULL,
    approved_at       DATETIME NULL,
    rejected_reason   VARCHAR(500) NULL,
    cancelled_at      DATETIME NULL,
    renewed_from_id   BIGINT UNSIGNED NULL,
    notes             TEXT NULL,
    created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bookings_no (booking_no),
    KEY idx_bookings_customer (customer_id),
    KEY idx_bookings_status (status),
    KEY idx_bookings_dates (start_date, end_date),
    CONSTRAINT fk_bookings_centre FOREIGN KEY (centre_id) REFERENCES centres (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_category FOREIGN KEY (seat_category_id) REFERENCES seat_categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_requested_by FOREIGN KEY (requested_by) REFERENCES accounts (id) ON DELETE SET NULL,
    CONSTRAINT fk_bookings_created_by FOREIGN KEY (created_by) REFERENCES staff_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_bookings_approved_by FOREIGN KEY (approved_by) REFERENCES staff_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_bookings_renewed_from FOREIGN KEY (renewed_from_id) REFERENCES bookings (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE booking_seats (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id    BIGINT UNSIGNED NOT NULL,
    seat_id       BIGINT UNSIGNED NOT NULL,
    unit_price    DECIMAL(12,2) NOT NULL COMMENT 'price locked at booking time',
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    start_time    TIME NULL,
    end_time      TIME NULL,
    allocated_at  DATETIME NULL,
    released_at   DATETIME NULL COMMENT 'set on handover / cancellation / early exit',
    created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_booking_seats (booking_id, seat_id),
    KEY idx_booking_seats_overlap (seat_id, start_date, end_date),
    CONSTRAINT fk_booking_seats_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_seats_seat FOREIGN KEY (seat_id) REFERENCES seats (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE booking_facilities (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id    BIGINT UNSIGNED NOT NULL,
    facility_id   BIGINT UNSIGNED NOT NULL,
    qty           DECIMAL(8,2) NOT NULL DEFAULT 1,
    unit_price    DECIMAL(12,2) NOT NULL,
    gst_rate      DECIMAL(5,2)  NOT NULL DEFAULT 18.00,
    amount        DECIMAL(12,2) NOT NULL,
    created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_booking_facilities (booking_id, facility_id),
    CONSTRAINT fk_booking_facilities_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_facilities_facility FOREIGN KEY (facility_id) REFERENCES facilities (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE checkins (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id      BIGINT UNSIGNED NOT NULL,
    seat_id         BIGINT UNSIGNED NOT NULL,
    checked_in_at   DATETIME NOT NULL,
    checked_out_at  DATETIME NULL,
    handled_by      BIGINT UNSIGNED NULL,
    notes           VARCHAR(255) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_checkins_booking (booking_id),
    KEY idx_checkins_seat (seat_id, checked_in_at),
    CONSTRAINT fk_checkins_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkins_seat FOREIGN KEY (seat_id) REFERENCES seats (id) ON DELETE RESTRICT,
    CONSTRAINT fk_checkins_handled_by FOREIGN KEY (handled_by) REFERENCES staff_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE payments (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id    BIGINT UNSIGNED NOT NULL,
    customer_id   BIGINT UNSIGNED NOT NULL,
    kind          VARCHAR(10)  NOT NULL COMMENT 'advance | deposit | rent | addon',
    mode          VARCHAR(20)  NOT NULL COMMENT 'App\\Enums\\PaymentMode',
    reference_no  VARCHAR(100) NULL,
    amount        DECIMAL(12,2) NOT NULL,
    paid_on       DATE NOT NULL,
    status        VARCHAR(12)  NOT NULL DEFAULT 'pending' COMMENT 'pending | verified | rejected | refunded',
    logged_by     BIGINT UNSIGNED NULL,
    verified_by   BIGINT UNSIGNED NULL,
    verified_at   DATETIME NULL,
    remarks       VARCHAR(500) NULL,
    created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_payments_booking (booking_id),
    KEY idx_payments_customer (customer_id),
    KEY idx_payments_status (status, paid_on),
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_logged_by FOREIGN KEY (logged_by) REFERENCES staff_users (id) ON DELETE SET NULL,
    CONSTRAINT fk_payments_verified_by FOREIGN KEY (verified_by) REFERENCES staff_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
